### ISSUE TITLE
App not more available?

### ISSUE THREAD

**Issue by r15ch13** [AwestruckStudios/Gen6#44]
Hey, is this app not more available in play store? :(

**Comment by Dawctah** [comment]
God damn, I love this Pokedex. I got a new phone so I wanted to get this app again, but, low and behold, it's gone. I guess that makes my old phone just a Pokedex then

**Comment by r15ch13** [comment]
You can still download it on http://cmfp.info/

**Comment by FedeX15** [comment]
That website doesn't work anymore

**Comment by LogicalDesign** [comment]
I was able to upload it again, without sprites.

https://play.google.com/store/apps/details?id=com.awestruckstudios.pkmn
